-- SUPABASE SETUP — Mohamed & Amira Guest Wishes
-- This is a completely separate table from any previous wedding invitation.
-- Run this ONCE in the same Supabase SQL Editor used by the project.

create table if not exists public.wishes_mohamed_amira (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 500),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.wishes_mohamed_amira enable row level security;

drop policy if exists "Mohamed Amira - Anyone can read approved wishes" on public.wishes_mohamed_amira;
create policy "Mohamed Amira - Anyone can read approved wishes"
on public.wishes_mohamed_amira
for select
to anon
using (approved = true);

drop policy if exists "Mohamed Amira - Anyone can submit wishes" on public.wishes_mohamed_amira;
create policy "Mohamed Amira - Anyone can submit wishes"
on public.wishes_mohamed_amira
for insert
to anon
with check (
  approved = true
  and char_length(name) between 1 and 60
  and char_length(message) between 1 and 500
);

create index if not exists wishes_mohamed_amira_created_at_idx
on public.wishes_mohamed_amira (created_at desc);
